// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface ICaregoryFields {
  /** 名前 */
  name: string;

  /** Slug */
  slug: string;
}

export interface ICaregory extends Entry<ICaregoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'caregory';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface INewsFields {
  /** 掲載日 */
  postedAt: string;

  /** タイトル */
  title: string;

  /** 内容 */
  content: Document;
}

export interface INews extends Entry<INewsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'news';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProductFields {
  /** 商品名 */
  name: string;

  /** Slug */
  slug: string;

  /** カテゴリー */
  category: Entry<{ [fieldId: string]: unknown }>;

  /** 説明 */
  description?: string | undefined;

  /** 金額 */
  prices: string[];

  /** 画像 */
  imageUrl: Asset;

  /** 掲載日 */
  createdAt: string;

  /** 注釈 */
  notes?: string[] | undefined;
}

export interface IProduct extends Entry<IProductFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'product';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'caregory' | 'news' | 'product';

export type LOCALE_CODE = 'ja-JP';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'ja-JP';
